
defaults: &job-defaults
  docker:
    - image: circleci/php:7.3-fpm-node-browsers-legacy 

jobs:
    build:
        <<: *job-defaults

        steps:
            - checkout
            - run: 'echo "what up!"'
