version: '3'
services:

    mongo:
        container_name: newstash-mongo-container
        image: mongo:4

    mysql:
        container_name: newstash-mysql-container
        image: mysql:8

        environment:
            MYSQL_ROOT_PASSWORD: bookstash
            MYSQL_DATABASE: bookstash
            MYSQL_USER: bookstash
            MYSQL_PASSWORD: bookstash
        ports:
            - "${MYSQL_PORT}:3306"

        volumes:
            - "${MYSQL_DATA_PATH}:/var/lib/mysql"
            - "${MYSQL_BINLOG_PATH}:/var/lib/mysql-binlogs"
            - "${APP_PATH}/data/conf.d:/etc/mysql/conf.d"

    php:
        container_name: newstash-php-container
        image: newstash-php-image

        build:
            context: ../
            dockerfile: docker/php/Dockerfile

        volumes:
            - "${APP_PATH}:/var/www/html/phpapp"

        environment:
            MONGODB_URL: "${MONGODB_URL}"
            MONGODB_DB: "${MONGODB_DB}"

            MAILER_URL: "${MAILER_URL}"

            APP_ENV: dev
            APP_SECRET: devsecretdevsecretdevsecret
            DATABASE_URL: "mysql://bookstash:bookstash@mysql:3306/bookstash"
            DATABASE_URL: "${DATABASE_URL}"

            AWS_REGION: "${AWS_REGION}"
            AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
            AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
            AWS_ASSOCIATE_TAG: "${AWS_ASSOCIATE_TAG}"

            FACEBOOK_APP_ID: "${FACEBOOK_APP_ID}"
            FACEBOOK_SECRET: "${FACEBOOK_SECRET}"
            GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
            GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
            GAQ_ID: "${GAQ_ID}"

        depends_on:
            - mysql
            - mongo

    ssh:
        container_name: newstash-ssh-container-${ENV}"
        image: "newstash-ssh-image-${ENV}"
        build: ../docker/ssh

        environment:
            TUNNEL_TARGET: "${TUNNEL_TARGET}"
            TUNNEL_USER: "${TUNNEL_USER}"
            TUNNEL_PORT: "${TUNNEL_PORT}"

        expose:
            - "3306"
        volumes:
            - "~/.ssh:/home/tunnel/.ssh"

        networks:
            - bookstash

