version: '3'
services:
    mysql:
        container_name: newstash-mysql-container
        image: mysql:8

        environment:
            MYSQL_ROOT_PASSWORD: bookstash
            MYSQL_DATABASE: bookstash
            MYSQL_USER: bookstash
            MYSQL_PASSWORD: bookstash
        ports:
            - "${MYSQL_PORT}:3306"

        volumes:
            - "${MYSQL_DATA_PATH}:/var/lib/mysql"
            - "${MYSQL_BINLOG_PATH}:/var/lib/mysql-binlogs"
            - "${APP_PATH}/data/conf.d:/etc/mysql/conf.d"

    php:
        container_name: newstash-php-container
        build: ../docker/php
        image: newstash-php-image

        volumes:
            - "${APP_PATH}:/var/www/html/phpapp"

        environment:
            MONGODB_URL: "${MONGODB_URL}"
            MONGODB_DB: "${MONGODB_DB}"

            APP_ENV: dev
            APP_SECRET: devsecretdevsecretdevsecret
            DATABASE_URL: "mysql://bookstash:bookstash@mysql:3306/bookstash"
            DATABASE_URL: "${DATABASE_URL}"

            AWS_REGION: "${AWS_REGION}"
            AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
            AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
            AWS_ASSOCIATE_TAG: "${AWS_ASSOCIATE_TAG}"

            FACEBOOK_APP_ID: "${FACEBOOK_APP_ID}"
            GOOGLE_API_KEY: "${GOOGLE_API_KEY}"
            GOOGLE_APP_ID: "${GOOGLE_APP_ID}"
            GAQ_ID: "${GAQ_ID}"
            AMZN_AFFILIATE: "${AMZN_AFFILIATE}"

        depends_on:
            - mysql

    nginx:
        container_name: newstash-nginx-container
        build: ../docker/nginx
        image: newstash-nginx-image
        ports:
            - "${APP_PORT}:80"
        volumes:
            - "${APP_PATH}:/var/www/html/phpapp"
        depends_on:
            - php

    mongo:
        container_name: newstash-mongo-container
        image: mongo:4

