version: '3'
services:

    mongo:
        container_name: newstash-mongo-container
        image: mongo:4

    mysql:
        container_name: newstash-mysql-container
        image: mysql:8

        environment:
            MYSQL_ROOT_PASSWORD: bookstash
            MYSQL_DATABASE: bookstash
            MYSQL_USER: bookstash
            MYSQL_PASSWORD: bookstash
        ports:
            - "${MYSQL_PORT}:3306"

        volumes:
            - "${MYSQL_DATA_PATH}:/var/lib/mysql"
            - "${MYSQL_BINLOG_PATH}:/var/lib/mysql-binlogs"
            - "${APP_PATH}/data/conf.d:/etc/mysql/conf.d"

    ssh:
        container_name: newstash-ssh-container-${ENV}"
        image: "newstash-ssh-image-${ENV}"
        build: ../docker/ssh

        environment:
            TUNNEL_TARGET: "${TUNNEL_TARGET}"
            TUNNEL_USER: "${TUNNEL_USER}"
            TUNNEL_PORT: "${TUNNEL_PORT}"

        expose:
            - "3306"
        volumes:
            - "~/.ssh:/home/tunnel/.ssh"

        networks:
            - bookstash

