
eight_points_guzzle:
    # (de)activate logging/profiler; default: %kernel.debug%
    logging: false

    clients:
        aws_webservice:
            base_url: "http://webservices.amazon.com/onca/xml"

