framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    #csrf_protection: ~
    #http_method_override: true

    # uncomment this entire section to enable sessions
    session:
        handler_id: ~
#        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler

    #esi: ~
    #fragments: ~
    php_errors:
        log: true

    templating:
        engines: ['twig', 'php']

