framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    #csrf_protection: ~
    #http_method_override: true

    # uncomment this entire section to enable sessions
    session:
        cookie_lifetime: 2592000 # 30 days
        gc_maxlifetime: 2592000 # 30 days
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\MongoDbSessionHandler

    #esi: ~
    #fragments: ~
    php_errors:
        log: true

    templating:
        engines: ['twig', 'php']

