limenius_react:
    # Other options are "server_side" and "client_side"
    default_rendering: "both"

    serverside_rendering:
        # In case of error in server-side rendering, throw exception
        fail_loud: false

        # Replay every console.log message produced during server-side rendering
        # in the JavaScript console
        # Note that if enabled it will throw a (harmless) React warning
        trace: false

        # Mode can be `"phpexecjs"` (to execute Js from PHP using PhpExecJs),
        # or `"external"` (to rely on an external node.js server)
        # Default is `"phpexecjs"`
        mode: "phpexecjs"

        # Location of the server bundle, that contains React and React on Rails.
        # null will default to `%kernel.root_dir%/Resources/webpack/server-bundle.js`
        # Only used with mode `phpexecjs`
        server_bundle_path: "%kernel.root_dir%/../var/webpack/server-bundle.js"

        # Only used with mode `external`
        # Location of the socket to communicate with a dummy node.js server.

        # More info: http://php.net/manual/en/function.stream-socket-client.php
        # Example of node server:
        # https://github.com/Limenius/symfony-react-sandbox/blob/master/app/Resources/node-server/server.js
        # null will default to `unix://%kernel.project_dir%/var/node.sock`
        server_socket_path: null

        cache:
            enabled: false
            # name of your app, it is the key of the cache where the snapshot will be stored.
            key: "app"
