twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    globals:
        facebook_app_id: '%env(resolve:FACEBOOK_APP_ID)%'
        google_client_id: '%env(resolve:GOOGLE_CLIENT_ID)%'
        gaq_id: '%env(resolve:GAQ_ID)%'
        amzn_affiliate: '%env(resolve:AMZN_AFFILIATE)%'

