Query:
  type: object
  config:
    fields:
      work:
        type: Work
        args:
          id:
            type: Int
        resolve: '@=resolver("workResolver", [info, args["id"], args])'

      edition:
        type: Edition
        args:
          asin:
            type: String
        resolve: '@=resolver("editionResolver", [info, args["asin"], args])'

      format:
        type: Format
        args:
          id:
            type: Int
        resolve: '@=resolver("formatResolver", [info, args["id"], args])'

      post:
        type: Post
        args:
          id:
            type: Int
        resolve: '@=resolver("postResolver", [info, args["id"], args])'

      comment:
        type: Comment
        args:
          id:
            type: Int
        resolve: '@=resolver("commentResolver", [info, args["id"], args])'

      user:
        type: User
        args:
          id:
            type: Int
        resolve: '@=resolver("userResolver", [info, args["id"], args])'

      browseNode:
        type: BrowseNode
        args:
          id:
            type: Int
        resolve: '@=resolver("browseNodeResolver", [info, args["id"], args])'

