Query:
  type: object
  config:
    fields:
      work:
        type: Work
        args:
          id:
            type: Int
        resolve: '@=resolver("workResolver", [info, args["id"], args])'

      edition:
        type: Edition
        args:
          asin:
            type: String
        resolve: '@=resolver("editionResolver", [info, args["asin"], args])'
