Work:
  type: object
  config:
    resolveField: '@=resolver("workResolver", [info, value, args])'
    fields:
      id:
        type: "Int!"
      title:
        type: "String"
      editions:
        type: editionConnection
        argsBuilder: "Relay::ForwardConnection"
      front_edition:
        type: Edition
      similar_works:
        type: workConnection
        argsBuilder: "Relay::ForwardConnection"

workConnection:
  type: relay-connection
  config:
    nodeType: Work!

