#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

facebook_login:
    path: /login/check-facebook

google_login:
    path: /login/check-google

graphqlite_bundle:
    resource: '@GraphqliteBundle/Resources/config/routes.xml'
