services:
    _defaults:
        public: true

    # If you need to access services in a test, create an alias
    # and then fetch that alias from the container. As a convention,
    # aliases are prefixed with test. For example:
    #
    # test.App\Service\MyService: '@App\Service\MyService'

    test.App\Service\Apa\ProductParser: '@App\Service\Apa\ProductParser'
    test.App\Service\BookParser: '@App\Service\BookParser'
    test.App\Service\Data\FrontFinder: '@App\Service\Data\FrontFinder'
    test.App\Service\Data\WorkGroomer: '@App\Service\Data\WorkGroomer'
    test.App\Service\EditionManager: '@App\Service\EditionManager'
    test.App\Service\LeadManager: '@App\Service\LeadManager'
