services:
    _defaults:
        public: true

    # If you need to access services in a test, create an alias
    # and then fetch that alias from the container. As a convention,
    # aliases are prefixed with test. For example:
    #
    # test.App\Service\MyService: '@App\Service\MyService'

    test.App\Service\Apa\Broker: '@App\Service\Apa\Broker'
    test.App\Service\Apa\ProductParser: '@App\Service\Apa\ProductParser'
    test.App\Service\Auth\NewstashUserProvider: '@App\Service\Auth\NewstashUserProvider'
    test.App\Service\Data\EditionLeadPicker: '@App\Service\Data\EditionLeadPicker'
    test.App\Service\Data\FrontFinder: '@App\Service\Data\FrontFinder'
    test.App\Service\Data\WorkGroomer: '@App\Service\Data\WorkGroomer'
    test.App\Service\EditionManager: '@App\Service\EditionManager'
    test.App\Service\ReviewManager: '@App\Service\ReviewManager'
    test.App\Service\RatingManager: '@App\Service\RatingManager'
    test.App\Service\ScoreManager: '@App\Service\ScoreManager'
    test.App\Service\ReviewLikeManager: '@App\Service\ReviewLikeManager'
    test.App\Service\ReaditManager: '@App\Service\ReaditManager'
    test.App\Service\Export: '@App\Service\Export'
    test.App\Service\Export\BrowseNode: '@App\Service\Export\BrowseNode'
    test.App\Service\Export\Work: '@App\Service\Export\Work'
    test.App\Service\Mongo: '@App\Service\Mongo'
    test.App\Service\Mongo\BrowseNode: '@App\Service\Mongo\BrowseNode'
    test.App\Service\Mongo\Work: '@App\Service\Mongo\Work'
    test.App\Service\Mongo\News: '@App\Service\Mongo\News'
